
//선언


//COLOR 
#define ORANGE /*FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_RED |*/ BACKGROUND_RED |BACKGROUND_GREEN | BACKGROUND_RED
#define BLUE  BACKGROUND_BLUE
#define PURPLE BACKGROUND_RED | BACKGROUND_BLUE 
#define RED   BACKGROUND_RED
#define GREEN BACKGROUND_GREEN
#define STARTCOLOR FOREGROUND_GREEN
#define YELLOW BACKGROUND_GREEN|BACKGROUND_RED
#define WHITE  FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_GREEN
#define INTESIFIED FOREGROUND_INTENSITY // text color is intensified
#define SETRESOLUTION system("mode con:cols=40 lines=20");
#define FULLRESOLUTION SetConsoleDisplayMode(GetStdHandle(STD_OUTPUT_HANDLE),CONSOLE_FULLSCREEN_MODE,NULL);
